// ============================================================
// LARP Language — Transpiler
// Converts a LARP AST into clean, readable JavaScript.
// Preserves source location info for source maps.
// ============================================================

import * as AST from '../parser/ast';

interface Output {
  lines: string[];
  indent: number;
}

export class Transpiler {
  private out: Output = { lines: [], indent: 0 };
  // track which identifiers are in a blueprint context (for this.X)
  private blueprintFields: string[] = [];
  private inBlueprint = false;
  private asyncDepth = 0;
  // track error variable per try block
  private errorVar: string | null = null;
  // track loop depth for outer breaks
  private loopDepth = 0;
  // track declared variables per scope to distinguish declaration vs reassignment
  private declaredVars: Set<string>[] = [new Set()];

  transpile(program: AST.Program): string {
    this.emit(`// Generated by LARP transpiler — https://larplang.dev`);
    this.emit(`(async function() {`);
    this.indent();
    this.emit(`const __larp = require('./runtime/helpers.js');`);
    this.emitBlank();

    for (const stmt of program.body) {
      this.emitStatement(stmt);
    }

    this.dedent();
    this.emit(`})().catch(__e => { console.error(__e); process.exit(1); });`);

    return this.out.lines.join('\n');
  }

  // ── Statements ─────────────────────────────────────────────────────────────
  private emitStatement(stmt: AST.Statement): void {
    switch (stmt.kind) {
      case 'SetStatement':              return this.emitSet(stmt);
      case 'SayStatement':              return this.emitSay(stmt);
      case 'IfStatement':               return this.emitIf(stmt);
      case 'WhileStatement':            return this.emitWhile(stmt);
      case 'ForEachStatement':          return this.emitForEach(stmt);
      case 'RepeatStatement':           return this.emitRepeat(stmt);
      case 'FunctionDeclaration':       return this.emitFunction(stmt);
      case 'BlueprintDeclaration':      return this.emitBlueprint(stmt);
      case 'ReturnStatement':           return this.emitReturn(stmt);
      case 'TryStatement':              return this.emitTry(stmt);
      case 'StopAndSayStatement':       return this.emitStopAndSay(stmt);
      case 'CheckStatement':            return this.emitCheck(stmt);
      case 'WriteStatement':            return this.emitWrite(stmt);
      case 'BringInStatement':          return this.emitBringIn(stmt);
      case 'ShareStatement':            return this.emitShare(stmt);
      case 'ServerBlock':               return this.emitServerBlock(stmt);
      case 'RouteHandler':              return this.emitRouteHandler(stmt);
      case 'RespondStatement':          return this.emitRespond(stmt);
      case 'StartServerStatement':      return this.emitStartServer(stmt);
      case 'ConnectDatabaseStatement':  return this.emitConnectDb(stmt);
      case 'RunQueryStatement':         return this.emitRunQuery(stmt);
      case 'BreakStatement':            return this.emitBreak(stmt);
      case 'ContinueStatement':         return this.emitContinue(stmt);
      case 'MatchStatement':            return this.emitMatch(stmt);
      case 'StopProgramStatement':      return this.emit('process.exit(0);');
      case 'ExpressionStatement':       return this.emit(`${this.emitExpr(stmt.expression)};`);
    }
  }

  private emitSet(s: AST.SetStatement): void {
    const val = this.emitExpr(s.value);
    // Check if value has async operations
    const isAwaitable = this.isAsyncExpr(s.value);
    const prefix = isAwaitable ? 'await ' : '';

    if (s.constant) {
      this.emit(`const ${s.name} = ${prefix}${val};`);
      this.currentScope().add(s.name);
    } else if (this.isDeclared(s.name)) {
      // Already declared in this or an enclosing scope — reassign
      this.emit(`${s.name} = ${prefix}${val};`);
    } else {
      // First occurrence — declare with let
      this.emit(`let ${s.name} = ${prefix}${val};`);
      this.currentScope().add(s.name);
    }
  }

  private emitSay(s: AST.SayStatement): void {
    this.emit(`console.log(${this.emitExpr(s.value)});`);
  }

  private emitIf(s: AST.IfStatement): void {
    this.emit(`if (${this.emitExpr(s.condition)}) {`);
    this.indent();
    s.then.forEach(st => this.emitStatement(st));
    this.dedent();

    for (const ei of s.elseIfs) {
      this.emit(`} else if (${this.emitExpr(ei.condition)}) {`);
      this.indent();
      ei.body.forEach(st => this.emitStatement(st));
      this.dedent();
    }

    if (s.otherwise) {
      this.emit('} else {');
      this.indent();
      s.otherwise.forEach(st => this.emitStatement(st));
      this.dedent();
    }

    this.emit('}');
  }

  private emitWhile(s: AST.WhileStatement): void {
    this.loopDepth++;
    const label = this.loopDepth === 1 ? 'outerLoop: ' : '';
    this.emit(`${label}while (${this.emitExpr(s.condition)}) {`);
    this.indent();
    s.body.forEach(st => this.emitStatement(st));
    this.dedent();
    this.emit('}');
    this.loopDepth--;
  }

  private emitForEach(s: AST.ForEachStatement): void {
    this.loopDepth++;
    const label = this.loopDepth === 1 ? 'outerLoop: ' : '';
    this.emit(`${label}for (let ${s.variable} of ${this.emitExpr(s.iterable)}) {`);
    this.indent();
    s.body.forEach(st => this.emitStatement(st));
    this.dedent();
    this.emit('}');
    this.loopDepth--;
  }

  private emitRepeat(s: AST.RepeatStatement): void {
    this.loopDepth++;
    const label = this.loopDepth === 1 ? 'outerLoop: ' : '';
    const c = this.emitExpr(s.count);
    this.emit(`${label}for (let __i = 0; __i < ${c}; __i++) {`);
    this.indent();
    s.body.forEach(st => this.emitStatement(st));
    this.dedent();
    this.emit('}');
    this.loopDepth--;
  }

  private emitBreak(s: AST.BreakStatement): void {
    if (s.target === 'outer') {
      this.emit('break outerLoop;');
    } else {
      this.emit('break;');
    }
  }

  private emitContinue(s: AST.ContinueStatement): void {
    this.emit('continue;');
  }

  private emitMatch(s: AST.MatchStatement): void {
    this.emit(`switch (${this.emitExpr(s.value)}) {`);
    this.indent();
    for (const c of s.cases) {
      this.emit(`case ${this.emitExpr(c.value)}:`);
      this.indent();
      c.body.forEach(st => this.emitStatement(st));
      this.emit('break;');
      this.dedent();
    }
    if (s.otherwise) {
      this.emit('default:');
      this.indent();
      s.otherwise.forEach(st => this.emitStatement(st));
      this.emit('break;');
      this.dedent();
    }
    this.dedent();
    this.emit('}');
  }

  private emitFunction(s: AST.FunctionDeclaration): void {
    const isAsync = s.isAsync || this.containsAsync(s.body);
    const asyncKw = isAsync ? 'async ' : '';
    const params  = s.params.map(p =>
      p.defaultValue ? `${p.name} = ${this.emitExpr(p.defaultValue)}` : p.name
    ).join(', ');

    this.emit(`${asyncKw}function ${s.name}(${params}) {`);
    this.indent();
    // New scope — params are pre-declared
    this.pushScope();
    s.params.forEach(p => this.currentScope().add(p.name));
    const prevAsync = this.asyncDepth;
    if (isAsync) this.asyncDepth++;
    s.body.forEach(st => this.emitStatement(st));
    this.asyncDepth = prevAsync;
    this.popScope();
    this.dedent();
    this.emit('}');
    this.emitBlank();
    // Register function name in enclosing scope
    this.currentScope().add(s.name);
  }

  private emitBlueprint(s: AST.BlueprintDeclaration): void {
    const ext = s.parent ? ` extends ${s.parent}` : '';
    this.emit(`class ${s.name}${ext} {`);
    this.indent();

    // constructor
    const fields = s.fields.join(', ');
    this.emit(`constructor(${fields}) {`);
    this.indent();
    if (s.parent) this.emit(`super(${fields});`);
    s.fields.forEach(f => this.emit(`this.${f} = ${f};`));
    this.dedent();
    this.emit('}');
    this.emitBlank();

    // methods (with field access rewriting)
    const prevFields     = this.blueprintFields;
    const prevInBlueprint = this.inBlueprint;
    this.blueprintFields = s.fields;
    this.inBlueprint     = true;

    for (const method of s.methods) {
      const isAsync = method.isAsync || this.containsAsync(method.body);
      const asyncKw = isAsync ? 'async ' : '';
      const params  = method.params.map(p =>
        p.defaultValue ? `${p.name} = ${this.emitExpr(p.defaultValue)}` : p.name
      ).join(', ');
      this.emit(`${asyncKw}${method.name}(${params}) {`);
      this.indent();
      this.pushScope();
      method.params.forEach(p => this.currentScope().add(p.name));
      const prevAsync = this.asyncDepth;
      if (isAsync) this.asyncDepth++;
      method.body.forEach(st => this.emitStatement(st));
      this.asyncDepth = prevAsync;
      this.popScope();
      this.dedent();
      this.emit('}');
      this.emitBlank();
    }

    this.blueprintFields = prevFields;
    this.inBlueprint     = prevInBlueprint;

    this.dedent();
    this.emit('}');
    this.emitBlank();
  }

  private emitReturn(s: AST.ReturnStatement): void {
    const isAwaitable = this.isAsyncExpr(s.value);
    const prefix = isAwaitable ? 'await ' : '';
    this.emit(`return ${prefix}${this.emitExpr(s.value)};`);
  }

  private emitTry(s: AST.TryStatement): void {
    this.emit('try {');
    this.indent();
    s.body.forEach(st => this.emitStatement(st));
    this.dedent();

    const errName = s.errorVar ?? '__err';
    this.emit(`} catch (${errName}) {`);
    this.indent();
    const prev = this.errorVar;
    this.errorVar = errName;
    s.handler.forEach(st => this.emitStatement(st));
    this.errorVar = prev;
    this.dedent();
    this.emit('}');
  }

  private emitStopAndSay(s: AST.StopAndSayStatement): void {
    this.emit(`throw new Error(${this.emitExpr(s.message)});`);
  }

  private emitCheck(s: AST.CheckStatement): void {
    const actual   = this.emitExpr(s.actual);
    const expected = this.emitExpr(s.expected);
    const srcText  = `${actual} is equal to ${expected}`;
    this.emit(`__larp.check(${actual}, ${expected}, ${JSON.stringify(srcText)});`);
  }

  private emitWrite(s: AST.WriteStatement): void {
    this.emit(`import('fs').then(fs => fs.writeFileSync(${this.emitExpr(s.path)}, ${this.emitExpr(s.content)}, 'utf8'));`);
  }

  private emitBringIn(s: AST.BringInStatement): void {
    const alias = s.alias ?? this.pathToAlias(s.path);
    // Built-in stdlib modules
    const builtins: Record<string, string> = {
      math:    `'./stdlib/helpers.js'`,
      helpers: `'./stdlib/helpers.js'`,
      server:  `'./stdlib/server.js'`,
      db:      `'./stdlib/database.js'`,
      http:    `'./stdlib/http.js'`,
      ai:      `'./stdlib/ai.js'`,
      files:   `'./stdlib/files.js'`,
    };
    const key = s.path.replace(/['"]/g, '').replace('./', '').replace('.larp', '');
    const isLarp = s.path.includes('.larp');
    const req = builtins[key] ?? (isLarp ? JSON.stringify(s.path.replace('.larp', '.js')) : JSON.stringify(s.path));
    
    // Use require for synchronous CommonJS resolution (works with pkg snapshots)
    this.emit(`const ${alias} = require(${req});`);
  }

  private emitShare(s: AST.ShareStatement): void {
    this.emit(`export { ${s.name} };`);
  }

  private emitServerBlock(_s: AST.ServerBlock): void {
    this.emit(`const __express = require('./stdlib/server.js').express;`);
    this.emit(`const __app = __express();`);
    this.emit(`__app.use(__express.json());`);
    this.emitBlank();
  }

  private emitRouteHandler(s: AST.RouteHandler): void {
    const method  = s.method.toLowerCase();
    const path_   = this.emitExpr(s.path);
    const reqVar  = s.reqVar ?? '__req';
    this.emit(`__app.${method}(${path_}, async (${reqVar}, __res) => {`);
    this.indent();
    this.emit(`try {`);
    this.indent();
    const prevAsync = this.asyncDepth; this.asyncDepth++;
    s.body.forEach(st => this.emitStatement(st));
    this.asyncDepth = prevAsync;
    this.dedent();
    this.emit(`} catch (__e) { __res.status(500).json({ error: __e.message }); }`);
    this.dedent();
    this.emit(`});`);
    this.emitBlank();
  }

  private emitRespond(s: AST.RespondStatement): void {
    this.emit(`return __res.json(${this.emitExpr(s.value)});`);
  }

  private emitStartServer(s: AST.StartServerStatement): void {
    const port = this.emitExpr(s.port);
    this.emit(`__app.listen(${port}, () => {`);
    this.indent();
    this.emit(`console.log(\`✓ LARP app running on port ${port === '__port' ? '${' + port + '}' : port}\`);`);
    this.dedent();
    this.emit(`});`);
  }

  private emitConnectDb(s: AST.ConnectDatabaseStatement): void {
    this.emit(`const ${s.varName} = require('./stdlib/database.js').connect(${this.emitExpr(s.url)});`);
  }

  private emitRunQuery(s: AST.RunQueryStatement): void {
    const params = s.params ? `, ${this.emitExpr(s.params)}` : ', []';
    const prefix = this.asyncDepth > 0 ? 'await ' : '';
    const assign = s.varName ? `let ${s.varName} = ` : '';
    this.emit(`${assign}${prefix}__db.query(${this.emitExpr(s.sql)}${params});`);
  }

  // ── Expression emitter ──────────────────────────────────────────────────────
  private emitExpr(expr: AST.Expression): string {
    switch (expr.kind) {
      case 'NumberLiteral':  return String(expr.value);
      case 'BooleanLiteral': return String(expr.value);
      case 'NothingLiteral': return 'null';

      case 'StringLiteral':
        if (expr.interpolated) {
          // Convert {name} to ${name} for template literals
          const body = expr.value.replace(/\{([a-zA-Z_]\w*)\}/g, (match, inner) => {
            const resolved = this.resolveField(inner.trim());
            return `\${${resolved}}`;
          });
          return '`' + body + '`';
        }
        return JSON.stringify(expr.value);

      case 'Identifier':
        return this.resolveField(expr.name);

      case 'BinaryExpression':
        return `(${this.emitExpr(expr.left)} ${this.mapOp(expr.op)} ${this.emitExpr(expr.right)})`;

      case 'UnaryExpression':
        return expr.op === 'not' ? `(!${this.emitExpr(expr.expr)})` : `(-${this.emitExpr(expr.expr)})`;

      case 'CallExpression':
        return `${this.emitExpr(expr.callee)}(${expr.args.map(a => this.emitExpr(a)).join(', ')})`;

      case 'MethodCallExpression': {
        const obj    = this.emitExpr(expr.object);
        const method = expr.method;
        const args   = expr.args.map(a => this.emitExpr(a)).join(', ');
        // Special handling for LARP list operations
        switch (method.toLowerCase()) {
          case 'add':      return `${obj}.push(${args})`;
          case 'remove':   return `__larp.listRemove(${obj}, ${args})`;
          case 'contains': return `${obj}.includes(${args})`;
          case 'sorted':   return `__larp.sorted(${obj})`;
          case 'at':       return `${obj}[${args}]`;
          default:         return `${obj}.${method}(${args})`;
        }
      }

      case 'IndexExpression':
        return `${this.emitExpr(expr.object)}[${this.emitExpr(expr.index)}]`;

      case 'MemberExpression':
        return `${this.emitExpr(expr.object)}.${expr.property}`;

      case 'ListLiteral':
        return `[${expr.elements.map(e => this.emitExpr(e)).join(', ')}]`;

      case 'MapLiteral': {
        const entries = expr.entries.map(e => `${this.emitExpr(e.key)}: ${this.emitExpr(e.value)}`);
        return `{ ${entries.join(', ')} }`;
      }

      case 'NewBlueprintExpression': {
        const args = expr.args.map(a => this.emitExpr(a.value)).join(', ');
        return `new ${expr.name}(${args})`;
      }

      case 'AskAiExpression':
        return `(await require('./stdlib/ai.js').ask(${this.emitExpr(expr.prompt)}))`;

      case 'AwaitExpression':
        return this.asyncDepth > 0
          ? `(await ${this.emitExpr(expr.inner)})`
          : this.emitExpr(expr.inner);

      case 'ReadFileExpression':
        return `require('fs').readFileSync(${this.emitExpr(expr.path)}, 'utf8')`;

      case 'GetRequestExpression':
        return `(await (await fetch(${this.emitExpr(expr.url)})).json())`;

      case 'PostRequestExpression': {
        const bodyStr = expr.body ? `body: JSON.stringify(${this.emitExpr(expr.body)}), ` : '';
        return `(await (await fetch(${this.emitExpr(expr.url)}, { method: 'POST', headers: {'Content-Type':'application/json'}, ${bodyStr}})).json())`;
      }

      case 'GetEnvVarExpression':
        return `process.env[${this.emitExpr(expr.name)}]`;

      case 'SquareRootExpression':
        return `Math.sqrt(${this.emitExpr(expr.value)})`;

      case 'UppercaseExpression':
        return `(${this.emitExpr(expr.value)}).toUpperCase()`;

      case 'LowercaseExpression':
        return `(${this.emitExpr(expr.value)}).toLowerCase()`;

      case 'LengthOfExpression':
        return `(${this.emitExpr(expr.value)}).length`;

      case 'TypeOfExpression':
        return `__larp.typeOf(${this.emitExpr(expr.value)})`;

      case 'RoundExpression':
        return `Math.round(${this.emitExpr(expr.value)})`;

      case 'TrimExpression':
        return `(${this.emitExpr(expr.value)}).trim()`;

      case 'SplitExpression':
        return `(${this.emitExpr(expr.value)}).split(${this.emitExpr(expr.delimiter)})`;

      case 'JoinExpression':
        return `(${this.emitExpr(expr.list)}).join(${this.emitExpr(expr.delimiter)})`;

      case 'CurrentTimeExpression':
        return `new Date().toISOString()`;

      case 'ErrorMessageExpression': {
        const errName = this.errorVar ?? '__err';
        return `${errName}.message`;
      }

      case 'DoAtSameTimeExpression': {
        const taskExprs = expr.tasks.map(t => this.emitExpr(t)).join(', ');
        return `(await Promise.all([${taskExprs}]))`;
      }

      case 'NullCoalesceExpression':
        return `(${this.emitExpr(expr.left)} ?? ${this.emitExpr(expr.right)})`;

      case 'FormatCurrencyExpression':
        return `new Intl.NumberFormat('en-US', {style: 'currency', currency: 'USD'}).format(${this.emitExpr(expr.value)})`;

      case 'SeedRandomExpression':
        return `__larp.seedRandom(${this.emitExpr(expr.value)})`;

      case 'AskExpression':
        return `__larp.ask(${this.emitExpr(expr.prompt)})`;

      case 'AsNumberExpression':
        return `__larp.toNumber(${this.emitExpr(expr.value)})`;

      case 'AsTextExpression':
        return `String(${this.emitExpr(expr.value)})`;

      case 'CommandLineArgumentExpression': {
        const name = this.emitExpr(expr.name);
        const fallback = expr.fallback ? this.emitExpr(expr.fallback) : 'null';
        return `__larp.getArg(${name}, ${fallback})`;
      }

      default:
        return '/* unknown expression */';
    }
  }

  // ── Helpers ──────────────────────────────────────────────────────────────────

  // Map LARP operators to JS operators
  private mapOp(op: string): string {
    switch (op) {
      case 'and': return '&&';
      case 'or':  return '||';
      case '^':   return '**'; // handled separately via Math.pow for safety
      default:    return op;
    }
  }

  // In a blueprint method, bare field names become "this.fieldName"
  private resolveField(name: string): string {
    if (this.inBlueprint && this.blueprintFields.includes(name)) {
      return `this.${name}`;
    }
    return name;
  }

  // Heuristically detect if an expression produces a Promise
  private isAsyncExpr(expr: AST.Expression): boolean {
    switch (expr.kind) {
      case 'AwaitExpression':
      case 'AskAiExpression':
      case 'GetRequestExpression':
      case 'PostRequestExpression':
        return true;
      default:
        return false;
    }
  }

  // Detect if a block of statements contains any await-needing expressions
  private containsAsync(stmts: AST.Statement[]): boolean {
    return stmts.some(s => {
      if (s.kind === 'SetStatement')    return this.isAsyncExpr(s.value);
      if (s.kind === 'ReturnStatement') return this.isAsyncExpr(s.value);
      if (s.kind === 'ExpressionStatement') return this.isAsyncExpr(s.expression);
      if (s.kind === 'SayStatement')    return this.isAsyncExpr(s.value);
      return false;
    });
  }

  // Derive an alias from a module path: "./helpers.larp" → "helpers"
  private pathToAlias(path: string): string {
    return path
      .replace(/^\.\//, '')
      .replace(/\.larp$/, '')
      .replace(/[^a-zA-Z0-9_]/g, '_');
  }

  // ── Output helpers ────────────────────────────────────────────────────────────
  private emit(line: string): void {
    const pad = '  '.repeat(this.out.indent);
    this.out.lines.push(`${pad}${line}`);
  }

  private emitBlank(): void { this.out.lines.push(''); }
  private indent():   void { this.out.indent++; }
  private dedent():   void { this.out.indent = Math.max(0, this.out.indent - 1); }

  // ── Scope tracking (for let vs reassignment) ────────────────────────────────
  private pushScope(): void {
    this.declaredVars.push(new Set());
  }
  private popScope(): void {
    if (this.declaredVars.length > 1) this.declaredVars.pop();
  }
  private currentScope(): Set<string> {
    return this.declaredVars[this.declaredVars.length - 1];
  }
  private isDeclared(name: string): boolean {
    // Search all scopes from innermost to outermost
    for (let i = this.declaredVars.length - 1; i >= 0; i--) {
      if (this.declaredVars[i].has(name)) return true;
    }
    return false;
  }
}

export function transpile(program: AST.Program): string {
  return new Transpiler().transpile(program);
}
