// Generated by LARP transpiler — https://larplang.dev
(async function() {
  const __larp = require('./runtime/helpers.js');

  let numbers = [10, 20, 30];
  let callbacks = [];
  outerLoop: for (let n of numbers) {
    function capture() {
      return n;
    }

    callbacks.push(capture);
  }
  let results = [];
  outerLoop: for (let cb of callbacks) {
    let result = cb();
    results.push(result);
  }
  __larp.check(results[0], 10, "results[0] is equal to 10");
  __larp.check(results[1], 20, "results[1] is equal to 20");
  __larp.check(results[2], 30, "results[2] is equal to 30");
  console.log("Closure-in-loop test passed! Each callback captured its own value.");
})().catch(__e => { console.error(__e); process.exit(1); });