// Generated by LARP transpiler — https://larplang.dev
import * as __larp from './runtime/helpers.js';

let outer = 0;
outerLoop: while ((outer < 3)) {
  let inner = 0;
  while ((inner < 3)) {
    if ((outer == 1)) {
      break outerLoop;
    }
    if ((inner == 1)) {
      let inner = (inner + 1);
      continue;
    }
    console.log(((("Outer: " + outer) + " Inner: ") + inner));
    let inner = (inner + 1);
  }
  let outer = (outer + 1);
}
switch (outer) {
  case 1:
    console.log("Outer stopped at 1!");
    break;
  case 2:
    console.log("Outer stopped at 2!");
    break;
  default:
    console.log(("Outer stopped at " + outer));
    break;
}
let myName = (null ?? "Guest");
console.log(("Name: " + myName));
let money = new Intl.NumberFormat('en-US', {style: 'currency', currency: 'USD'}).format(15.5);
console.log(money);